title: Pupilla
description: "A multidisciplinary preprint archive inspired by Chiara Lubich's spirituality of unity."
# Update these URLs when you deploy to your custom domain
baseurl: "/pupilla"  # This is correct!
url: "https://pupillax.github.io"
google_analytics: "G-XXXXXXXXXX"  # Replace with your actual GA4 measurement ID

# Site metadata
author: Pupilla Team
email: info@pupilla.org
twitter: pupillaorg  # Optional: your Twitter handle
github: pupillax     # Optional: your GitHub username

# Collections
collections:
  pupilla-preprints:
    output: true
    permalink: /preprints/:name/

# Default settings for preprints
defaults:
  - scope:
      path: ""
      type: pupilla-preprints
    values:
      layout: preprint
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en_US
logo: /assets/images/logo.png
social:
  name: Pupilla
  links:
    - https://github.com/pupillax

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - .gitignore
  - .git
  - .sass-cache
  - _drafts

# Include files
include:
  - _pages

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Pagination disabled for now
# paginate: 10
# paginate_path: "/page:num/"

# Archive settings
archive:
  type: monthly
  layout: archive