title: Pupilla
description: "A multidisciplinary preprint archive with the aim of building bridges and striving for unity in diversity."

# Custom domain configuration
baseurl: ""  # Empty for custom domain
url: "https://pupilla.org"  # Your custom domain
google_analytics: "G-VETQ7ZZ4FM"

# Site metadata
author: Pupilla Team
email: info@pupilla.org
twitter: pupillaorg
github: pupillax

# Collections
collections:
  pupilla-preprints:
    output: true
    permalink: /preprints/:name/

# Default settings for preprints
defaults:
  - scope:
      path: ""
      type: pupilla-preprints
    values:
      layout: preprint
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en_US
logo: /assets/images/logo.png
social:
  name: Pupilla
  links:
    - https://github.com/pupillax

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing (removed CNAME from exclusions)
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - .git
  - .sass-cache
  - _drafts

# Include files
include:
  - _pages

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Archive settings
archive:
  type: monthly
  layout: archive