#!/usr/bin/env python3
"""Create / verify the per-language pages for articles and essays.

Every piece lists its languages in front matter (`languages: ["Català", "Español", "English"]`).
The first is the default and lives at the piece's normal URL. Each other language gets its own page
at <normal URL><code>/ — e.g. /essays/2026-quan-patti-va-coneixer-lleo/es/ — so it can be linked,
shared and indexed (with hreflang) on its own. GitHub Pages runs Jekyll in safe mode (no plugins), so
these pages are tiny stub files in language-versions/ that the layouts fill from the source piece.

    python3 scripts/make-language-pages.py            # write missing stubs, remove orphaned ones
    python3 scripts/make-language-pages.py --check    # exit 1 if anything is missing/orphaned (used by CI)

Run it whenever you add a language to a piece (or add a piece with several languages).
"""
import glob, os, re, sys

COLLECTIONS = {"_pupilla-preprints": ("preprints", "preprint"), "_pupilla-essays": ("essays", "essay")}
OUT = "language-versions"
CODES = {"english": "en", "italiano": "it", "italian": "it", "español": "es", "espanol": "es", "spanish": "es",
         "deutsch": "de", "german": "de", "français": "fr", "francais": "fr", "french": "fr",
         "català": "ca", "catala": "ca", "catalan": "ca", "português": "pt", "portugues": "pt",
         "portuguese": "pt", "日本語": "ja", "japanese": "ja"}

def code(name):
    n = name.strip().lower()
    return CODES.get(n, n[:2])

def front_matter(path):
    text = open(path, encoding="utf-8").read().replace("\r\n", "\n")
    m = re.match(r"---\s*\n(.*?)\n---\s*(?:\n|$)", text, re.S)
    return m.group(1) if m else ""

def languages(fm):
    m = re.search(r'(?m)^languages:\s*\[(.*?)\]\s*$', fm)
    if not m:
        return []
    return [x.strip().strip('"').strip("'") for x in m.group(1).split(",") if x.strip()]

def slug(path):
    return re.sub(r"[^a-z0-9]+", "-", os.path.splitext(os.path.basename(path))[0].lower()).strip("-")

want = {}   # stub path -> content
for folder, (url_dir, layout) in COLLECTIONS.items():
    for path in sorted(glob.glob(f"{folder}/*.md")):
        langs = languages(front_matter(path))
        for lang in langs[1:]:
            c = code(lang)
            base = f"/{url_dir}/{slug(path)}/"
            stub = f"{OUT}/{url_dir}--{slug(path)}--{c}.md"
            want[stub] = (f"---\nlayout: {layout}\nvariant_of: {base}\nlang_view: \"{lang}\"\npermalink: {base}{c}/\n---\n"
                          f"<!-- Generated by scripts/make-language-pages.py — do not edit; the layout fills this page from {base} -->\n")

have = set(glob.glob(f"{OUT}/*.md"))
missing = [p for p in want if p not in have or open(p, encoding="utf-8").read() != want[p]]
orphans = sorted(have - set(want))

if "--check" in sys.argv:
    for p in missing: print("missing or out of date:", p)
    for p in orphans: print("orphaned (no matching piece/language):", p)
    sys.exit(1 if (missing or orphans) else 0)

os.makedirs(OUT, exist_ok=True)
for p in missing:
    open(p, "w", encoding="utf-8").write(want[p]); print("wrote  ", p)
for p in orphans:
    os.remove(p); print("removed", p)
print(f"{len(want)} language pages in sync ({len(missing)} written, {len(orphans)} removed)")
